<?php
namespace Model;

class GameConst{
	//流程时间
	const GAME_TIME_ROLL_DICE = 3;
	const GAME_TIME_SHOW_RESULT = 7;
	const GAME_TIME_SHOW_REWARD = 7;
	const GAME_TIME_SHOW_LOTTERY = 3;
	const TIME_SHOW_STAND_USER_BET = 1;
	
	//server端回包命令
	const CMD_S_LOGIN = 0x101;
	const CMD_S_LOGOUT = 0x102;
	const CMD_S_USER_COUNT_UPDATE = 0x103;
	const CMD_S_GAME_DATA = 0x104;
	const CMD_S_FETCH_ROOM_DATA = 0X105;
	const CMD_S_GET_ROOM_STAND_LIST = 0X106;
	const CMD_S_USER_SIT = 0x110;
	const CMD_S_USER_STAND = 0X111;
	
	const CMD_S_GAME_READY = 0x217;
	const CMD_S_GAME_BET_START = 0x215;
	const CMD_S_GAME_BET_END = 0x212;
	const CMD_S_GAME_RESULT = 0x216;
	const CMD_S_GAME_REWARD = 0x214;
	
	const CMD_S_BET = 0x201;
	const CMD_S_BET_REPEAT = 0x202;
	const CMD_S_CANCEL_BET = 0x203;
	const CMD_S_BROADCAST_CANCEL_BET = 0x204;
	const CMD_S_BROADCAST_BET_SIT = 0x210;
	const CMD_S_BROADCAST_BET_STAND = 0x211;
	
	const CMD_S_SYSTEM_SIGN = 0X302;
	
	const CMD_S_FREIND_REQUEST = 0x401;
	const CMD_S_ACCEPT_FREIND_REQUEST = 0x402;
	const CMD_S_DEL_FRIEND = 0X403;
	
	const CMD_S_HEART_BEAT = 0x002;
	const CMD_S_CHAT = 0X003;
	const CMD_S_MAGIC_FACE = 0X004;
	const CMD_S_SEND_ACT_ITEM = 0X005;
	const CMD_S_BROADCAST_SEND_ACT_ITEM = 0X006;
	const CMD_S_SEND_MONEY = 0X007;
	const CMD_S_BROADCAST_SEND_MONEY = 0X008;
	
	const CMD_S_ADMIN= 0X888;
	
	const CMD_S_TEST = 0X889;
	
	//游戏币加减途径
	const MONEY_SOURCE_BET = 1127;
	const MONEY_SOURCE_BET_REWARD = 1126;
	const MONEY_SOURCE_LOTTERY_REWARD = 1156;
	const MONEY_SOURCE_SEND_MONEY = 14;
	const MONEY_SOURCE_ACCEPT_SEND_MONEY = 1;
	const MONEY_SOURCE_SEND_ACT_ITEM = 791;
	const MONEY_SOURCE_CANCEL_BET = 1164;
	
	//上次摇骰记录是否显示
	const SHOW_LAST_DICE_FALSE = 0;
	const SHOW_LAST_DICE_TRUE = 1;
	
	//系统命令
	const SYSTEM_SIGN_SERVER_UPDATE = 1;
	const SYSTEM_SIGN_ACCOUNT_MULTI_LOGIN = 2;
	const SYSTEM_SIGN_ACCOUNT_DISABLE = 3;
	const SYSTEM_SIGN_TABLE_COMBINE_BEGIN = 4;
	const SYSTEM_SIGN_TABLE_COMBINE_END = 5;
	const SYSTEM_SIGN_USER_EXIT_NO_BET = 6;
	
	//登录返回码
	const LOGIN_RET_OK = 0;
	const LOGIN_RET_ERR_MTKEY = 1;
	const LOGIN_RET_ERR_OTHER_GAME = 2;
	const LOGIN_RET_ERR_OTHER_SERVER = 3;
	const LOGIN_RET_ERR_ACCOUNT = 4;
	const LOGIN_RET_ERR_ACCOUNT_DISABLE = 5;
	const LOGIN_RET_ERR_ROOM_DATA = 6;
	const LOGIN_RET_ERR_TABLE_DATA = 7;
	const LOGIN_RET_ERR_SICBO_ROOM = 8;
	const LOGIN_RET_ERR_ASSET_LOW = 9;
	const LOGIN_RET_ERR_ASSET_HIGH = 10;
	
	//下注返回码
	const BET_RET_OK = 0;
	const BET_RET_TIME_FAIL = 1;
	const BET_RET_MONEY_NOT_ENOUGH = 2;
	const BET_RET_MAX_MONEY = 3;
	const BET_RET_ERROR_OTHER = 4;
	
	//
	const CANCEL_BET_OK = 0;
	const CANCEL_BET_ERR_ROOM_ST = 1;
	const CANCEL_BET_ERR_NO_BET = 2;
	const CANCEL_BET_ERR_MONEY = 3;
	
	//赠送互动道具返回码
	const ACT_ITEM_RET_OK = 0;
	const ACT_ITEM_RET_ERR_SELF_SEAT = 1;
	const ACT_ITEM_RET_ERR_TO_SEAT = 2;
	const ACT_ITEM_RET_ERR_MONEY_NOT_ENOUGH = 3;
	const ACT_ITEM_RET_ERR_DEC_MONEY = 4;
	
	//互动道具收费
	const ACT_ITEM_MONEY_FACTORY = 0.1;
	
	//赠送游戏币返回码
	const SEND_MONEY_RET_OK = 0;
	const SEND_MONEY_RET_ERR_SELF_SEAT = 1;
	const SEND_MONEY_RET_ERR_TO_SEAT = 2;
	const SEND_MONEY_RET_ERR_MONEY_NOT_ENOUGH = 3;
	const SEND_MONEY_RET_ERR_DEC_MONEY = 4;
	const SEND_MONEY_RET_ERR_WRONG_MEONY_AMOUNT = 5;
	
	//获取房间数据返回码
	const FETCH_ROOM_DATA_RET_OK = 0;
	const FETCH_ROOM_DATA_RET_ERROR_ROOM = 1;
	const FETCH_ROOM_DATA_RET_OTHER = 2;
	
	
	//mf用户金币变化统计
	const MF_MONEY_TYPE_BET = 1;
	const MF_MONEY_TYPE_BET_REWARD = 2;
	const MF_MONEY_TYPE_REPEAT_BET = 3;
	const MF_MONEY_LOTTERY_REWARD = 4;
	const MF_MONEY_CANCEL_BET = 5;
	
	//server状态
	const SERVER_ST_RUN = 0;
	const SERVER_ST_STOP = 1;
}